Deltares/hydromt

- hydromt/cli/main.py
- hydromt/data_adapter.py
- hydromt/models/model_api.py
- tests/test_cli.py
- tests/test_data_adapter.py
* add --models flag to hydromt main cli to print available model plugins
* add --dd flag to hydromt build and hydromt update to parse deltares data
* add deltares_data[bool] argument to DataCatalog in data_adapter.py and Model in models/model_api.py
* add cli_test.py for cli unit tests
fixes #11
> add deltares data to DataCatalog, Model API and cli

- docs/user_guide/data.rst
- examples/README.rst
- examples/delineate_basin.ipynb
- examples/read_raster_data.ipynb
- hydromt/__init__.py
- hydromt/data_adapter.py
- hydromt/models/model_api.py
- tests/test_basin_mask.py
* change instances of hydro_merit to merit_hydro (official name)
* bump artifact release (pre-release) to v0.0.3
> Merit hydro

- hydromt/cli/cli_utils.py
> fix parsing of multiple --opt from command line

- README.rst
- hydromt/cli/main.py
- hydromt/models/__init__.py
- hydromt/models/model_api.py
- hydromt/models/model_plugins.py
* log plugin version and distribution when initializing class
* print plugin version with hydromt --models
> keep and log plugin versions

- hydromt/__init__.py
- hydromt/cli/main.py
* fixes use of  single path without list notation in data_libs in config [global] section. To behaviour is now also similar to --deltares-data which overwrites the setting in the ini file.
* small fix of erroneous version number. This should solve the issue with the wrong folder name in the gh-pages branch.
> cli data_libs fix

- docs/changelog.rst
- hydromt/data_adapter.py
- Bugfix `DataAdapter.resolve_paths` with argument in root, fixes #78
- default GTiff lwz compression with `DataCatalog.export_data` method
- rename `DataAdapter.export_data` to `DataAdapter.to_file` to avoid confusion with `DataCatalog.export_data` method
- Bugfix `DataAdapter.__init__` setting None value in meta data
> various small fixes in data_adapter

- docs/changelog.rst
- hydromt/__init__.py
- hydromt/flw.py
- hydromt/log.py
- hydromt/models/model_api.py
- hydromt/raster.py
- hydromt/vector.py
- hydromt/workflows/basemaps.py
- pyproject.toml
- tests/conftest.py
- tests/test_basin_mask.py
- tests/test_flw.py
- tests/test_geo.py
- tests/test_raster.py
- improve `flw.reproject_hydrography_like`
- improve `flw.dem_adjust`
- improve log file handling
- add new rasterio inverse distance weighting method ("rio_idw") to `raster.interpolate_na`
- fix incorrect nodata values at valid cells from scipy.griddata method in `raster.interpolate_na`
- fix several warnings
> several improvements to flw, raster.interpolate_na and logging

- pyproject.toml
- tests/test_flw.py
- fix test after release of pyflwdir 0.5.4
This should fix the failing tests in #89 #90
> bump pyflwdir version

- docs/changelog.rst
- docs/user_guide/cli.rst
- examples/delineate_basin.ipynb
- hydromt/flw.py
- hydromt/models/model_api.py
- hydromt/workflows/basin_mask.py
- pyproject.toml
- tests/test_flw.py
> general setup_region method

- docs/changelog.rst
- hydromt/gis_utils.py
> add missing datum to utm_crs

- docs/changelog.rst
- hydromt/data_adapter.py
Some changes in get_data:
- variables also allowed to be a str instead of a list of str
- new DeprecationWarning for automatic renaming of single var array in get_data if variables is provided
> Small updates in get_data

- docs/changelog.rst
- hydromt/data_adapter.py
- tests/test_data_adapter.py
- fix key error in `resolve_paths` #121
- show yml entry when printing data source
- added source_names to `to_yml` method
> small fix / improvements data_adapter

- docs/changelog.rst
- hydromt/data_catalog.py
Pass predicate from get_geodataframe to get_data method for GeoDataFrame.
> pass predicate argument to get_data method

- docs/changelog.rst
- docs/user_guide/data_prepare_cat.rst
- hydromt/data_adapter/data_adapter.py
- tests/test_data_adapter.py
fixes #86; 
based on #131 and #134
> fix month and year formatting in yml paths 

- data/predefined_catalogs.yml
- docs/_static/theme-deltares.css
- docs/api.rst
- docs/changelog.rst
- docs/conf.py
- docs/user_guide/data_existing_cat.rst
- docs/user_guide/data_main.rst
- docs/user_guide/data_prepare_cat.rst
- docs/user_guide/intro.rst
- docs/user_guide/model_build.rst
- docs/user_guide/model_update.rst
- examples/reading_raster_data.ipynb
- examples/reading_vector_data.ipynb
- examples/working_with_raster.ipynb
- hydromt/cli/main.py
- hydromt/data_adapter/geodataset.py
- hydromt/data_adapter/rasterdataset.py
- hydromt/data_catalog.py
- hydromt/models/model_api.py
- tests/test_data_adapter.py
- tests/test_data_catalog.py
- predefined data catalogs through new yml file in data folder
- support for data archives
- new global "meta" section in yml file
fixes #62, #140
> restructure predefined data catalogs 

- .github/workflows/publish-pypitest.yml
- .github/workflows/publish.yml
- new test-pypi publish 
- fixed manual pypi publish workflows
fixes #42
> workflow for publishing to pip

- docs/changelog.rst
- hydromt/workflows/forcing.py
> Issue #189 xarray import

- docs/changelog.rst
- hydromt/models/model_api.py
> Fix #190 staticgeoms backward compatibility

- docs/changelog.rst
- hydromt/__init__.py
Post release 0.6.0 commits (dev version + changelog)
> Post release commit

- docs/getting_started/examples_index.rst
- examples/prep_data_catalog.ipynb
- examples/reading_point_data.ipynb
- examples/working_with_flow_directions.ipynb
- small typo 
- use pprint for docs rendering
- fix broken notebook link in examples_index
> Small notebook updates

- data/predefined_catalogs.yml
add era5 zarr data with more variables
see artifact data:
PR https://github.com/DirkEilander/hydromt-artifacts/pull/5 
release https://github.com/DirkEilander/hydromt-artifacts/releases/tag/v0.0.7
> update data_artifacts to v0.0.7

- docs/changelog.rst
- docs/conf.py
- hydromt/cli/cli_utils.py
- hydromt/cli/main.py
- hydromt/config.py
- tests/test_config.py
> fixed reading lists and none with config

- hydromt/cli/cli_utils.py
- hydromt/config.py
- tests/test_config.py
> fix eval setup_config 

- docs/changelog.rst
- docs/user_guide/data_overview.rst
- envs/hydromt-dev.yml
- envs/hydromt-min.yml
- envs/hydromt-test.yml
- examples/working_with_tiled_raster_data.ipynb
- hydromt/cli/main.py
- hydromt/data_adapter/caching.py
- hydromt/data_adapter/data_adapter.py
- hydromt/data_adapter/geodataset.py
- hydromt/data_adapter/rasterdataset.py
- hydromt/data_catalog.py
- hydromt/raster.py
- pyproject.toml
- tests/test_data_adapter.py
- tests/test_data_catalog.py
- tests/test_forcing.py
- tests/test_gis_utils.py
- tests/test_raster.py
This branch adds caching for tiled raster datasets.
@hboisgon can you review this part and then merge everything and release? Could you especially advise on the used xml parser to read vrt tiles? I used xml2dict, mostly for convenience (simple interface) and because I'm only interested in reading but I haven't check the performance against other parsers. If you think another parser is better / more in line with the FEWS branch I'm also happy to change / feel free to change that code.
> add vrt tile caching functionality

- .zenodo.json
- docs/changelog.rst
- docs/dev/contributing.rst
- envs/hydromt-min.yml
- hydromt/__init__.py
- hydromt/vector.py
I've updated the zenodo meta data file in preparation of the release.
This relates to https://github.com/openjournals/joss-reviews/issues/4897
> prep release v0.7.0

- hydromt/models/model_grid.py
> BUG: fix error if crs property of Model.grid is None

- hydromt/config.py
Relative paths in lists were not parsed correctly.
> small fix parsing paths in yml

- hydromt/models/model_api.py
fixes:
- method without arguments
> FIX: small bugs related to new yml ini files

- docs/changelog.rst
- hydromt/data_adapter/rasterdataset.py
- hydromt/raster.py
- tests/conftest.py
- tests/test_data_adapter.py
- tests/test_model.py
- tests/test_raster.py
> FIX: order of renaming var in get_rasterdataset

- hydromt/raster.py
> FIX: force writing crs and nodata attributes in interpolate_na 

- docs/changelog.rst
- hydromt/raster.py
- tests/test_raster.py
> ENH: add extrapolate argument to raster.interpolate_na

- docs/changelog.rst
- docs/dev/contributing.rst
- examples/data/vito_reclass.csv
- examples/grid_model_build.yaml
- hydromt/models/model_api.py
- hydromt/models/model_grid.py
- hydromt/models/model_mesh.py
- hydromt/raster.py
- hydromt/workflows/__init__.py
- hydromt/workflows/grid.py
- tests/data/parameters_data.yml
- tests/data/vito_mapping.csv
- tests/test_model.py
Some updates on GridModel:
- bugfix for #364 
- support creating a rotated grid in setup_grid
- allow to pass and run raster.gdal_compliant in Model._write_nc
> GridModel updates

- data/catalogs/deltares_data.yml
Fixes #355 
@hboisgon   provided the corrections in the issue themselves, I just applied them. 
I didn't double check that the new source urls are correct, since I trust Helene on this.
> update source urls in predefined catalogue

- pyproject.toml
Fixes #437 
Remove an unnecessary dev dependency 
> remove wheel as dependency

- hydromt/__init__.py
> Version bump

- docs/api.rst
- docs/changelog.rst
- hydromt/__init__.py
- hydromt/_compat.py
- hydromt/gis_utils.py
- hydromt/raster.py
- pyproject.toml
- tests/conftest.py
- tests/test_io.py
Fixes #410 
As noted in the attached issue, if this functionality is necessary it can be re-added in hydromt-wflow. Therefore I just removed the deprecated dependency group since they aren't used at all anymore 
> remove deprecated dependency group and associated code

- docs/user_guide/data_prepare_cat.rst
Fixes #468 
I simply added the exmaple that @hboisgon already provided to the documentation. There was already a description of `attrs` in the documentation so I'm not sure if anything more is necessary, if so feel free to put those in a comment and I'll try to address them.
> Docs attr example

- data/catalogs/deltares_data.yml
Fixes #480 
Solution is as suggested in the issue.
> Add rename to grdc entry

- docs/changelog.rst
- hydromt/models/model_api.py
Fixes #397 
From our discussion today during the sprint planning I understand that this should be enough to close the issue. If anything else also needs to be done on this please let me know.
> add model version attr to Model base object

- hydromt/gis_utils.py
fix [sonar-cloud detected non-functional code](https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=Deltares_hydromt&open=AYNbREBNf2Mi-5ffpH75)
> sonarcloud bugfix gis_utils.py

- docs/changelog.rst
- hydromt/data_adapter/data_adapter.py
- hydromt/data_adapter/rasterdataset.py
- hydromt/io.py
- hydromt/raster.py
- tests/test_data_adapter.py
Fixes #433 
Also added support for writing COG with overviews in `RasterDataset.to_raster`
> Support for writing COG and reading zoom levels from internal COG overviews

- hydromt/data_catalog.py
- tests/test_data_catalog.py
Fixes #522 
It broke the Wflow plugin and probably others. Just readded some code
> Readded contains

- docs/plugins.rst
Fixes #530 
Wasn't quite sure what text was necessary so I went with someing very simple. If anyone more knowledgabel on the subject would like to suggest something else I'd be happy to change it. 
> add simple delft3dfm description to docs

- docs/api.rst
- docs/changelog.rst
- docs/dev/plugin-quickstart.rst
- docs/dev/roadmap.rst
- docs/getting_started/installation.rst
- docs/user_guide/intro.rst
- docs/user_guide/model_overview.rst
- examples/working_with_models.ipynb
- examples/working_with_models_basics.ipynb
- examples/working_with_raster.ipynb
- hydromt/models/__init__.py
- hydromt/models/model_plugins.py
- hydromt/models/model_vector.py
- hydromt/vector.py
- pyproject.toml
- tests/conftest.py
- tests/test_api.py
- tests/test_cli.py
- tests/test_model.py
- tests/test_vector.py
Fixes #474 
Fixes #497 
See related issues
Because we are going to maybe write some generic methods, I changed that VectorModel geometry should be of type Polygon and not Point or Line. If this is not okay we can change but this will make the development of generic methods more complex.
> Vector model updates

- .github/workflows/publish-docker.yml
This doesn't actually necessarily fix the docker workflow, but it enables some more testing so it is required for that.
> Add manual dispatch for publish docker workflow for testing.

- .github/workflows/publish-docker.yml
- .github/workflows/test-docker.yml
Fixes #568 
Haven't tested the actuall release path yet, but we'll do that tomorrow. At least the workflow dispatch path does work. 
> Fix Docker publishing action

- docs/user_guide/model_config.rst
> fix document custumizable writing in build and update

- .github/workflows/docs.yml
add manual docs dispatch to test reverted docs release action
> add docs manual dispatch

- .github/workflows/refresh-cache.yml
> make docs cache path relative

- .github/workflows/docs.yml
- .github/workflows/refresh-cache.yml
> Sneaky docs cache fix

- .github/workflows/docs.yml
- .github/workflows/refresh-cache.yml
Fixed it finally, what was wrong that the `-M html` changed the write dir of sphinx.
> Fix docs workflow

- pyproject.toml
Fixes #610 
came up during feedstock analysis of the release. really surprised anything works without this. Pyyaml is a required dependency so I added it there, and stored the dependencies for good measure while I was at it. 
> Add pyaml as required dependency

- hydromt/cli/main.py
this method still needed to be updated. This method is not present here, but defined and used in the plug ins. This should probagly be documented or abstracted a bit better at some point. Later tho.
> Hot fix: update cli method

- docs/changelog.rst
- hydromt/cli/api.py
- hydromt/cli/cli_utils.py
- hydromt/cli/main.py
- hydromt/data_catalog.py
- hydromt/nodata.py
- hydromt/typing.py
- pyproject.toml
- tests/data/export_config.yml
- tests/data/test_sources.yml
- tests/test_cli.py
Fixes #528 
Most of the work was on the CLI part and correctly calling the existing `data_export` functionality. Some light typing were added, but I expect to do much more work on this when I work on the validation issue so I've not put too much work in that so far. I also briefly looked into mocking the CLI tests, but that turned out to be more work than I thought was appropriate for for this ticket so I've just made a separate ticket for that. 
> Implement export data via cli

- docs/changelog.rst
- hydromt/cli/main.py
- hydromt/models/model_api.py
- hydromt/typing.py
- hydromt/validators/__init__.py
- hydromt/validators/data_catalog.py
- hydromt/validators/model_config.py
- hydromt/validators/region.py
- pyproject.toml
- tests/data/test_model_config.yml
- tests/validators/test_data_catalog_validation.py
- tests/validators/test_model_config_validation.py
- tests/validators/test_region_validator.py
Fixes #236 
Use Pydantic models for validating rules about the data catalog. This PR has some limitations which I'll list below but also lays a lot of groundwork. I'm actually pretty happy with the results. When this gets merged I'll make tickets to address the limitations. In the spirit of agile I think it's better to just merge this now, and address the further issues down the line so we can keep iterating it as we add features to it. 
> Add validation methods for data catalog

- docs/changelog.rst
- hydromt/cli/main.py
- hydromt/validators/__init__.py
- hydromt/validators/model_config.py
- tests/test_cli.py
- tests/validators/test_data_catalog_validation.py
- tests/validators/test_model_config_validation.py
Fixes #637 
I've copied what I can from how the model code actually does this. I've done input argument checking where I could but this is not possible everywhere especially where dictionary arguments are taken. I think this is a nice result for now though. 
> Model config validation

- hydromt/__init__.py
- pixi.toml
> bump version post release

- .gitignore
Seems like I forgot to add `.pixi` to the gitignore. Whoops.
> add .pixi to gitignore

- docs/api.rst
- docs/changelog.rst
- hydromt/stats/skills.py
- tests/test_stats_skill.py
Fixes #609
While adding VE and RSR I also found some mistakes in pbias and mse (so rmse)
> Add new skills in stats

- pyproject.toml
Fixes current CI
Lock GCSFS at the current version
> upgrade gcsfs

- data/catalogs/deltares_data.yml
- docs/changelog.rst
> Updated deltares data catalog with new GADM fgb files

- .github/pull_request_template.md
- data/catalogs/changelog.rst
- data/catalogs/deltares_data.yml
- data/predefined_catalogs.yml
Updates to PR template to include a check for versioning the pre-defined data catalogs.
> Update pr template

- data/catalogs/changelog.rst
- data/catalogs/deltares_data.yml
> Add waterdemand dataset

- data/catalogs/deltares_data.yml
> Fix waterdemand

- data/catalogs/changelog.rst
- data/catalogs/deltares_data.yml
- docs/changelog.rst
- hydromt/data_adapter/data_adapter.py
- hydromt/data_catalog.py
- hydromt/validators/data_catalog.py
- tests/data/merged_esa_worldcover.yml
- tests/test_data_catalog.py
> Revert "Improve reproducibility dd"

- docs/changelog.rst
- hydromt/data_adapter/data_adapter.py
- hydromt/data_adapter/geodataset.py
- hydromt/data_adapter/rasterdataset.py
- hydromt/data_catalog.py
- tests/test_data_adapter.py
Fixes #731 
the no data strategy wasn't being passed or handled everywhere. this PR fixes that. 
> Handle nodata strategy in adapters more consistently

- .github/workflows/check-data-catalogs.yml
forgot to add the checkout step to the workflow. 
> add checkout to check workflow

- .github/workflows/test-docker.yml
- pyproject.toml
Fixes #744 
For whatever reason the new version that fixes this issue isn't being used so we'll just require it in our toml, so this should fix the problem. 
> require new version of sphinx

- docs/changelog.rst
- hydromt/raster.py
- tests/test_raster.py
Fixes #760 
Relax assumption that all dataset variables must have the same dimensions.
> fix check dims for ds with multiple vars

- hydromt/raster.py
> fix review comments #761

- docs/changelog.rst
- hydromt/io.py
- tests/test_data_adapter.py
- tests/test_io.py
Fixes #776 
Add geometry mask back
No
> Fix vector mask

- docs/changelog.rst
- hydromt/data_adapter/rasterdataset.py
> relax warning in rasterdataset

- .github/workflows/check-data-catalogs.yml
- .github/workflows/docs.yml
- .github/workflows/pixi_auto_update.yml
- .github/workflows/tests.yml
- pixi.lock
- pixi.toml
Pin the version number in CI for pixi. 0.16.0 is bugged.
> Pin pixi to 0.15.2

- .github/workflows/check-data-catalogs.yml
- .github/workflows/docs.yml
- .github/workflows/pixi_auto_update.yml
- .github/workflows/tests.yml
- pixi.lock
- pixi.toml
> Main pin pixi 0.15.2

- .github/workflows/tests.yml
- docs/api.rst
- hydromt/driver/__init__.py
- hydromt/driver/netcdf_driver.py
- pyproject.toml
- tests/drivers/test_netcdf_driver.py
Fixes #855 
Added NetCDF driver with unittest
> Add NetCDF driver

- hydromt/_typing/type_def.py
- hydromt/data_adapter/rasterdataset.py
- hydromt/data_catalog.py
- hydromt/data_source/data_source.py
- hydromt/data_source/geodataframe.py
- hydromt/data_source/rasterdataset.py
- hydromt/drivers/geodataframe_driver.py
- hydromt/drivers/netcdf_driver.py
- hydromt/drivers/pyogrio_driver.py
- hydromt/drivers/rasterdataset_driver.py
- hydromt/drivers/zarr_driver.py
- hydromt/metadata_resolver/convention_resolver.py
- hydromt/metadata_resolver/metadata_resolver.py
- tests/data_sources/test_geo_data_frame_source.py
- tests/data_sources/test_raster_dataset_source.py
- tests/drivers/test_netcdf_driver.py
- tests/drivers/test_pyogrio_driver.py
- tests/drivers/test_zarr_driver.py
- tests/metadata_resolvers/test_convention_resolver.py
Fixes #880
changelog in data/changelog.rst
> Data source to file

- hydromt/drivers/geodataset/xarray_driver.py
- hydromt/gis/vector.py
- tests/conftest.py
- tests/drivers/geodataset/test_xarray_driver.py
- tests/drivers/raster/test_raster_xarray_driver.py
> Geodataset xarray driver

- docs/api.rst
- hydromt/drivers/geodataframe/table_driver.py
- tests/drivers/geodataframe/test_pyogrio_driver.py
- tests/drivers/geodataframe/test_table_driver.py
Fixes #924 
Created a "table" driver for the previously called "vector" driver.
> add geodataframe table driver

- tests/components/test_tables_component.py
Fixes #946 
just enable the test. it worked straight out of the box. 
> renable table integration test

- hydromt/_typing/metadata.py
- hydromt/data_source/geodataframe.py
- hydromt/data_source/rasterdataset.py
- tests/data_sources/test_geo_dataframe_source.py
Fixes #941 
Renable tests, and make sure they get the attributes from the correct object.
> renable and fixt geodataframe source test

- hydromt/data_catalog/uri_resolvers/convention_resolver.py
- hydromt/data_catalog/uri_resolvers/metadata_resolver.py
- hydromt/data_catalog/uri_resolvers/raster_tindex_resolver.py
Resolver had no up-to-date docs
Added docs for the `transform` methods.
> add docs on resolve method

- docs/changelog.rst
- hydromt/__init__.py
> bump version to dev

- pixi.toml
- pyproject.toml
builds fail by introduction of numpy 2.0
> restrict numpy to version 1

- docs/assets/example_catalog.yml
- docs/conf.py
- docs/guides/advanced_user/data_prepare_cat.rst
- docs/parse_predefined_catalogs.py
- pixi.lock
- pixi.toml
Fixes part of the documentation
Rewrote part of the `prepare_datacatalog.rst`
I wanted to test parts of the code snippets that we add. I therefore added `doctest` as a sphinx plugin. The `doctest` builder will test the snippets that are marked to be tested. Not all snippets can easily be converted, because they talk about a hypothetical situation, in this case a situation where there are both different versions and providers of the same code.
> update prepare data catalog docs

- docs/guides/user_guide/installation.rst
Fixes #675 
As documented in the issue, apparently the install guide was too long so I've simplified it in the style of the hydromt-wflow install guide that was linked as an example
> Simplify Install guide

- examples/prep_data_catalog.ipynb
- examples/reading_point_data.ipynb
- examples/reading_raster_data.ipynb
- examples/reading_tabular_data.ipynb
- examples/reading_vector_data.ipynb
- examples/working_with_flow_directions.ipynb
- examples/working_with_geodatasets.ipynb
- examples/working_with_raster.ipynb
- examples/working_with_tiled_raster_data.ipynb
- hydromt/gis/raster.py
Fixes Examples focusing on `DataCatalog`
> update examples focusing on `DataCatalog`

- .github/workflows/docs.yml
- Dockerfile
Fixes #1071
made an error in echoing the variable into the github env. this should fix that
> fix github env syntax

- hydromt/data_adapter/data_adapter.py
- tests/test_data_adapter.py
> fix resolve  path

- .github/workflows/pre-commit_auto_update.yml
pre-commit is outdated. It's good if we check monthly if it can be updated.
File copied directly from the Ribasim code base.
> automatically update pre-commit

- .binder/Dockerfile
- .github/pull_request_template.md
- .github/workflows/check-data-catalogs.yml
- .github/workflows/create-release-artifacts.yml
- .github/workflows/docs.yml
- .github/workflows/pixi_auto_update.yml
- .github/workflows/prep-release.yml
- .github/workflows/test-docker.yml
- .github/workflows/tests.yml
- .sonarcloud.properties
- docs/changelog.rst
- docs/guides/core_dev/dev_install.rst
- docs/guides/user_guide/installation.rst
- pixi.lock
- pyproject.toml
Fixes #540 
Add support for python 3.12 and 3.13
> Update python versions

- hydromt/__init__.py
Revert version to 1.0.0, because that's how the release pipeline wants it.
> Decrement version to 1.0.0, because that's the currently released version

- docs/changelog.rst
- hydromt/data_catalog/drivers/dataframe/pandas_driver.py
- hydromt/data_catalog/sources/dataframe.py
> Remove metadata from pandas driver

- README.rst
- docs/guides/core_dev/contributing.rst
> Change codecov to sonarqube in docs

- .github/workflows/pre-commit_auto_update.yml
- .pre-commit-config.yaml
- data/src/era5_download_resample_convert.py
- examples/prep_data_catalog.ipynb
- examples/working_with_raster.ipynb
- hydromt/_typing/type_def.py
- hydromt/_utils/unused_kwargs.py
- hydromt/data_catalog/drivers/_preprocessing.py
- hydromt/model/processes/region.py
- tests/gis/test_gis_utils.py
- tests/io/test_io.py
Make sure that the pre-commit hook always creates a PR, even when the pre-commit fails. That way you can check-out the branch, make the changes to fix the pre-commit, and update the PR with some manual changes if needed.
> Pre commit update

- .github/workflows/pixi_auto_update.yml
Adds information about the updated packages in the pixi.lock file in the PR on auto update
See https://github.com/Deltares/hydromt/pull/1160
> Add description to PR for pixi auto-update

- pixi.lock
- pyproject.toml
Use branch coverage for SonarQube
> Add --cov-branch to pytest

- hydromt/data_catalog/drivers/geodataframe/pyogrio_driver.py
Unneccessary warning produced by the pyogrio driver.
The metadata doesnt have to be passed in the unused warnings function, as the crs, that is present in the metadata, can be used within the driver. Which it now is, as the crs will be used from the data catalog to set the projection of the GeoDataFrame.
The predicate keyword argument is only passed into this read function to ensure compatibility. Therefore it does not have to be passed into the unused kwargs function. As nothing is passed to that function anymore, it can be deleted.
No.
> Pyogrio driver unused kwargs fix

- data/catalogs/test_data_catalog.py
> updated test_data_catalog.py script

- docs/guides/user_guide/hydromt_cli.rst
- docs/guides/user_guide/model_update.rst
- docs/overview/quick_overview.rst
- hydromt/cli/main.py
Should be merged when hydromt_wflow is v1 compatible after merging this: https://github.com/Deltares/hydromt_wflow/pull/539
see https://github.com/Deltares/hydromt_wflow/pull/535 for more context.
> fix: update hydromt_wflow cli examples
