Deltares/hydromt

hydromt/models/model_api.py, tests/test_model_api.py
I added a test_model_api method in model_api.py.
It should be able to do most of the checks. The limit I see now is that for config nested dictionnaries, I only test on two levels if the elements in config are dictionnaries. I guess this is enough.
I also added unittests of the function in test_model_api.py
@DirkEilander hope this is what you had in mind?
=> Model API compliance test

docs/changelog.rst, hydromt/__init__.py, hydromt/cli/main.py, hydromt/models/__init__.py, hydromt/models/model_plugins.py, hydromt/workflows/basin_mask.py
Plugins are only loaded when import MODELS or xxxModel from hydromt.models and not when importing hydromt as before. This avoids potential circular dependencies and makes partial imports of plugins possible (e.g. import hydromt_wflow.worksflows).
=> load plugins lazy to avoid circular dependencies

binder/environment.yml, docs/changelog.rst, envs/hydromt-dev.yml, envs/hydromt-min.yml, envs/hydromt-test.yml, hydromt/io.py, hydromt/merge.py, hydromt/models/model_api.py, pyproject.toml, tests/test_raster.py
- mask option in merge.merge method for improved open_raster_from_tindex. The method reads and merges data from tiles with different projections summarized in a gdal tindex geometry within a bounding box. The destination crs and resolution are now determined based on the tile with the largest overlap with the destination bounding box, which basically keeps most of the data as is. 
- dropped dask version pins
- remove IOError in set_config (IOErrors should not be in set_ methods, only write_ methods)
=> improve raster mosaic

docs/user_guide/data.rst
The position of the tileindex argument was set under kwargs and not mosaic_kwargs. Documentation of this section modified accordingly
=> Description of hydromt.io.open_raster_from_tindex

docs/changelog.rst, hydromt/data_adapter.py
- drop non-serializable entries from yml file when writing data catalog to avoid it getting corrupt
- data catalog yml entries get priority over local files or folders with the same name in the data_adapter.get_* methods
and multi-file rasterdatasets are only supported through the data catalog yml file
=> data adapter improvements

hydromt/raster.py
Too many unnecessary warnings message of type "No numerical nodata value found, skipping set_nodata" were issued by HydroMT.
This happened in two places:
- calls to raster.geometry_mask (example in get_rasterdataset if geom is not None)
- calls to raster.nodata (calling a set_nodata even if both rio.nodata and rio.encoded_nodata are None already)
=> Remove unnecessary nodata value not found warnings

docs/changelog.rst, hydromt/models/model_plugins.py, hydromt/raster.py
Bugfix #210 dim0 removal in raster._check_dimensions
While testting I did not have xugrid and found a bug in ep.load in model_plugins.py if an exception is found while loading entrypoints.
=> Bugfix #210

docs/changelog.rst, examples/export_data.ipynb, hydromt/data_catalog.py, hydromt/models/model_api.py, hydromt/models/model_grid.py, hydromt/models/model_lumped.py, hydromt/models/model_mesh.py, tests/test_data_catalog.py, tests/test_model.py
- strict and consistent read/write mode policy
- do not automatically read hydromt_data.yml file in model root #237
- fix `DataCatalog.to_yml` and `DataCatalog.export()` with relative path and add meta section #230
=> Datacatalog fixes and strict read/write mode in Model class

docs/changelog.rst, examples/export_data.ipynb, hydromt/data_adapter/geodataset.py, hydromt/data_adapter/rasterdataset.py, hydromt/data_catalog.py, tests/test_data_adapter.py, tests/test_data_catalog.py
=> ENH: support exporting individual variables in DataCatalog.export_data

hydromt/data_adapter/caching.py, hydromt/data_catalog.py
This PR makes it possible to work with artifact data (required for many tests!) when offline. Currently it relies on the online predefined data catalog yaml file. With this change is caches that file to ~/.hydromt_data and uses the cached version if now internet connection is available.
A small modification to the _copyfile method was required to be able to download text data (this didn't work with shutil.copyfileobj in combination with the request.get().raw attribute). I've tested this still works with other data formats as well.
=> ENH: cache predefined data catalogs file to be able to work offline

hydromt/gis_utils.py
Since numpy 1.20.0, aliases of builtin types is deprecated. In most cases, this was not a problem, but one line in `write_map` used np.bool. This functionality is now removed from numpy, and is failing the hydromt_wflow tests. This PR fixes this issue, by changing `np.bool` with `bool` and `np.bool_`. See https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
=> Fix deprecated numpy function

docs/changelog.rst, docs/user_guide/model_region.rst, hydromt/workflows/basin_mask.py
Fixes #297 
Turns out it was a bug. the list [xy] from region was parsed into tuples in a lot of different if else conditions in get_basin_geometry or basin_map. Fixed by converting to tuples more upstream in the code.
=> fix subbasin xy without snapping options

.github/ISSUE_TEMPLATE/documentation_improvement.yaml, .github/pull_request_template.md, .pre-commit-config.yaml, .yamlfmt, data/catalogs/deltares_data.yml, data/catalogs/gcs_cmip6_data.yml, docs/conf.py, tests/data/test_sources.yml
Fixes #426 
The previous pre-commit hook for yaml formatting did not work on windows for whatever reason. So in order to remedy this I moved us over to the google pre-commit hook, which should be better maintained. If I recall correctly the google formatter has a bit fewer options for customization, but I tuned it to be as close to the format rules we already have. It made a few small changes, but overall should be fine, and now it works on windows as well, so all in all, I think this is fine. 
=> Fix yamlfmt

tests/test_data_adapter.py
Fixes #408 
The problem seemed to be that Dask by default uses a light weight thread scheduler for it's workloads. This is lightweight but threads are flaky in python at best, and to the best of my understanding this caused the test to occasionally hang because at least two Dask threads were getting into a deadlock (each thread waiting on the other to complete something so they can continue their own work). Because this is quite a hard to reproduce issue and is arguably an upstream issue, I decided to go for the easy fix and just use the synchronous scheduler in Dask which should not run into this problem. If we run into the issue in more places we can start thinking of a more fundamental solution. 
Because the issue is quite hard to reproduce I can't be 100% certain that this solves the …
=> Fix haning test

docs/changelog.rst, hydromt/data_adapter/caching.py, hydromt/data_catalog.py, tests/test_data_catalog.py
Fixes #413
Make sure _uri_validator accepts Path ojbects and is called with str.
=> _uri_validator accepts Path objects

.github/workflows/test-docker.yml, Makefile, docs/dev/dev_install.rst, make_env.py, pyproject.toml
Fixes #436 
Simply adjusted the make commands to use the `mamba` api instead of `micromamba` as that should be the default. Tested the install on windows, and that seems to go fine as well, so should all be good 
=> Fix `make dev` for mamba 

docs/changelog.rst, hydromt/vector.py, tests/test_vector.py
Fixes #415 
Added a new `index_merge` argument in `GeoDataset.from_gdf` and `GeoDataArray.from_gdf` to decide whether to merge based on the gdf index (default) or the intersection of both the gdf and data indices. Other merge options do not make sense as a GeoDataset/Array should contain a coordinate with geometries which cannot/should not have missing values. An error is raised in both cases if there is no overlap in indices between both datasets.
=> from_gdf: gdf vs data index

.github/workflows/docs.yml, .github/workflows/tests.yml, make_env.py, pyproject.toml
Fixes #447 
Not sure why but the inclusion of the "defaults" channel seems to make everything go haywire, so this is removed. Should fix all the CIs. It doesn't seem necessary so I can't remember why it got included, but it should all be okay after this PR is merged again. 
=> remove defaults channel from conda

docs/_static/switcher.json, docs/changelog.rst, docs/conf.py, docs/dev/contributing.rst
Fixes #188
simplay followed the link and followed the docs. Works just fine. The only downside is that the older versions of the docs don't have this added so once you switch, the menu for it disapears. Can go back and retroactively add this back to the older versions if necessary, but this could give issues with reproducability (e.g. not sure if this plugin is compatable with older doc versions.) 
Currently the url of the version switcher points to a file that will be deleted when the branch is deleted. Once this is approved, I'll switch it over to where the file will live after merging. This will temporary break the docs between update and merging as the file needs to be found for the docs to be generated, but should this should be fixed as soon as the merge is complete, so it should be …
=> Add version switch to docs

examples/reading_vector_data.ipynb, pyproject.toml, tests/conftest.py, tests/test_flw.py
Fixes #285 
The CRS with epsg code 3785 is deprecated (see https://epsg.io/3785) and therefore automatically replaced by 3857 when reading vector data with the old epsg code since fiona version > 1.8.22. Updating the test data to the new epsg seems the right solution. Since fiona is not directly imported in the HydroMT (it's a dependency of geopandas) I've removed it from our dependencies. 
=> BUG: update deprecated epsg code (3785) in test data to release fiona pin

docs/changelog.rst, hydromt/models/model_api.py, hydromt/models/model_grid.py, hydromt/models/model_lumped.py, tests/test_model.py
Fixes #472 
I moved the initialization of the model component to the property definition. 
When called the first time, we initialize the component and try to read it if in read-mode.
From the second time forward a call of the property returns the initialized component without trying to read.
Now we can use the `set_` methods again inside the `read_` methods like we used to do.
This could also break code downstream, if the internal properties are called (e.g. `self._maps` instead of `self.maps`). In the new implementation calling the internal static properties should be restricted to the `set_` methods and the dynamic property methods only which happen in the core. Hence, an easy fix should be to replace all calls to the internal static property by the dynamic property.
=> Avoid RecursionError when using Model.set methods inside Model.read methods

.github/workflows/tests.yml, hydromt/models/model_mesh.py, hydromt/workflows/basin_mask.py, pyproject.toml, tests/conftest.py, tests/test_model.py
=> add io and extra to testing in ci again

hydromt/models/model_api.py, hydromt/utils.py, tests/test_model.py
Fixes #253 
I'll be honest, this is not the most elegant solution I've ever found but it does do the job. I'm not a fan of this design (the dictionary) but this solution does work, and refactoring the dictionary away could have unintended consequences that I don't have insight into so for now this is okay. However, if this continues to have problems, then we should seriously consider a redesign of this part of the system. 
The problem was that the dictionary was only being updated using the direct parent class and not any of the ancestors. This was fixed by using the `__mro__` (Method Resolution Order) attribute, which gives access to basically all ancestor classes as opposed to only the direct parent.
=> Fix api inherritence of models using __mro__

.gitignore, docs/changelog.rst, hydromt/models/model_api.py, hydromt/models/model_grid.py, hydromt/models/model_lumped.py, hydromt/models/model_mesh.py, hydromt/models/model_network.py, tests/test_model.py
Fixes #377 
Copied and extended the code from Wflow as referenced in the issue. It seemed like a good idea to support more file types than just csv, so I implemented so common ones, but others can easily be added if necessary. 
=> add tables property to base model class

docs/changelog.rst, hydromt/io.py, tests/test_io.py
Fixes #508
In case the locations are read with geopandas and not io.open_vector_from table, other geometry than points can be passed. Removed a hardcoded assert_gtype = Point that was left in io.open_geodataset.
=> Bugfix: reading geodataset with other type than point locations for vector driver

hydromt/data_adapter/data_adapter.py, hydromt/data_adapter/dataframe.py, hydromt/data_adapter/geodataframe.py, hydromt/data_adapter/geodataset.py, hydromt/data_adapter/rasterdataset.py, hydromt/data_catalog.py, hydromt/models/model_api.py, tests/test_data_catalog.py, tests/test_model.py
Fixes #501 
Implementing a `__contains__` method allows for checking if data catalog contains a source with `name in catalog`
Also fixed the used_only argument of the to_yml method. This did no work properly as it only saved the source name and not the catalog or version.
=> Support for checking if DataCatalog "contains" a source 

docs/changelog.rst, docs/user_guide/data_prepare_cat.rst, hydromt/data_adapter/data_adapter.py, hydromt/data_adapter/dataframe.py, hydromt/data_adapter/geodataframe.py, hydromt/data_adapter/geodataset.py, hydromt/data_adapter/rasterdataset.py, hydromt/stats/extremes.py, pyproject.toml, tests/data/aws_esa_worldcover.yml, tests/data/merged_esa_worldcover.yml, tests/test_data_adapter.py
Fixes #499 
The `filesystem` property is now detected from the path (and hence optional in the data catalog).
The `storage_options` argument is set outside the `driver_kwargs` argument as it is not passed to the driver, but to the fsspec filesystems method. (needs to be updated in future data catalogs, now backwards compatible).
=> Support for http and other filesystems in path of data source

.github/workflows/docs.yml
Committing the build docs to the gh-pages deletes all files resulting in 404 errors.
The hydromt version cannot be read from the package in the conda base environment, hence the results are written to the gh-pages root.
=> fix docs version

.github/workflows/refresh-cache.yml
NA
We have a few flaky tests that can sometimes fail due to time out. This can prevent the cache being generated needed for the test CI to be run. I'd rather not, but assuming that tests on main should always pass is one of the loosest assumptions I think we can make in this context. Therefore, with this PR, the cache CI should always save the cache, regardless of the test outcome. If we ever manage to address the flaky tests, this should be removed again. 
=> always upload chaches on main

docs/api.rst, hydromt/gis_utils.py, hydromt/raster.py, hydromt/utils.py, tests/test_raster.py
I profiled the `to_slippy_tiles` methods to better understand its poor performance. This was mostly the result of many different calls to the `pyproject.CRS.from_user_input method` when `self.crs` was called in addition to other raster properties. And to some extend because of the gdal based reproject instead of simple numpy based averaging for coarsening of the raster.
- Improves performance of raster accessor by caching raster properties `crs`, `transform`, `res`, `origin`, and `rotation`
- in `to_slippy_tiles`  support different dtypes and use numpy based average upscaling
- Clean up of some remainder PCR Raster methods
=> Raster cache props

.binder/Dockerfile, .github/workflows/test-docker.yml, pyproject.toml, tests/test_raster.py
remove gdal dependency 
links to https://github.com/Deltares/hydromt_delft3dfm/issues/13
gdal is not directly imported, so not a direct dependency of hydromt and could potentially make hydromt pip installable.
=> remove explicit gdal dep

docs/changelog.rst, hydromt/raster.py, tests/test_raster.py
Fixes #298 
Add a better error message if writing no data fails in raster.py
=> Add better error message on incompatible nodata

docs/getting_started/installation.rst, examples/README.rst
Fixes #546 
Fixes #465 
I've decided to solve both of the issues above by simply explaining in the examples that either you need a dev installation for the latest examples, or you should check out the examples of the version you have installed. I have done this for a couple of reasons:
1. if you want to run the examples you already need the repository, at which point, making a dev install is a small step beyond that
2. given that you already have the repo, we can assume the user has at least some very rudimentary git knowledge, so checking out the tag of the version installed which has the versions of the examples they want is a simple operations
3. We also have binder for running the examples. 
4. it is by far the simplest option on our side. 
One other thing we could do is make the …
=> Update example installation instructions in docs

hydromt/data_adapter/data_adapter.py, hydromt/data_adapter/rasterdataset.py, hydromt/data_catalog.py, tests/test_data_adapter.py, tests/test_data_catalog.py
- the detection of zoom levels from COG files was broken because of initialization of zoom_levels with an empty dict instead of None
- DataCatalog.get_*data methods did not work for files that are not on the local filesystem because of a file exist check. This check is also done downstream in the get_data method so I removed it at this stage.
- the filesystem is now inferred from the path if not set. This is required for proper access of cloud data without a data catalog entry
=> fix small issues with access cloud and cog files

.github/dependabot.yml, pyproject.toml
Fixes #614 
Since numpy 1.22 is EOL now, it would be good to update so that people don't use unsupported versions. Since 1.22's EOL is in 2 months (source: https://endoflife.date/numpy) I've decided to just bump it to 1.23 directly. this gives us 8 months before we need to update further so that seems like a good idea. Currently the numpy version esolves to 1.24 (in my environment) so using 1.23 should be fine for the time being. 
I've also added a dependabot alerting so that we are notified of these things a bit more frequently. Sadly it doesn't support conda dependencies, but since our conda dependencies mirror that of pip (it's built from pyproject.toml) having alerts for pip EOLs is a close enough analog imo, we can always investigate further from there if necessary. 
Add any …
=> Bump numpy

.pre-commit-config.yaml, docs/dev/contributing.rst, hydromt/raster.py, pyproject.toml, tests/test_data_catalog.py
Ruff just implemented a formater that is compatible with black (they claim 99.9% the same behavior) but is an order of magnitude faster. Since we also already install ruff for the pre-commit hooks and CIs it also simplifies that process. Therefore it would make sense to switch to that. 
=> Move formatting from black to ruff

pyproject.toml
pyogrio is imported in gis_utils.py. As it will be mandatory to use with geopandas soon anyways, why not move it to required packages instead of doing dynamic imports?
moved the dependency in the pyproject.toml
=> move pyogrio to mandatory imports

data/catalogs/aws_data.yml, docs/changelog.rst, hydromt/data_adapter/dataframe.py, hydromt/data_adapter/geodataframe.py, hydromt/data_adapter/geodataset.py, hydromt/data_adapter/rasterdataset.py, hydromt/data_catalog.py, hydromt/models/model_vector.py, hydromt/typing.py, tests/data/stac/catalog.json, tests/data/stac/chirps_global/catalog.json, tests/data/stac/chirps_global/chirps_global/chirps_global.json, tests/data/stac/gadm_level1/catalog.json, tests/data/stac/gadm_level1/gadm_level1/gadm_level1.json, tests/data/stac/gtsmv3_eu_era5/catalog.json, tests/data/stac/gtsmv3_eu_era5/gtsmv3_eu_era5/gtsmv3_eu_era5.json, tests/test_data_catalog.py
Fixes #404 
This is a rudimentary implementation and more sophisticated conversions are probably possible, but would have to get refined further first depending on use cases. One limitation is that currently because we determine dataadapter type based on the media type of the asset, and Raster and Geodataset share some media types, these aren't being determined correctly. I think it's best to still merge this now and make a ticket to distinguish them better so that we can still get this out and gather more feedback on it. 
=> Implement from stac for data catalog

hydromt/gis_utils.py
Fixes #624
I added a quick fix for global rasterdatasets that have rounding errors regarding their outer boundaries. The fix could be a more elegant, but for now it fixes the issue #624, which was breaking for @dalmijn.  
=> Transform boundary fix

tests/test_data_catalog.py
Tests was broken due to different paths handling on windows. Shouldn't have made a difference on the actual behavior, but it's better to have the tests fixed. Now works with Paths so should be cross platform. 
=> fix to_stac test on widows

docs/changelog.rst, hydromt/data_adapter/rasterdataset.py, hydromt/gis_utils.py, hydromt/raster.py, pyproject.toml, tests/test_data_catalog.py, tests/test_gis_utils.py, tests/test_raster.py
Fixes #624 
The error was because the the meridian_offset function created an irregular grid as some cells where incorrectly shifted.
The solution checks if the grid is global (x spans 360 degrees) before shifting which is required to keep a regular grid.
In addition we check if the grid is regular when computing the resolution to avoid these funny downstream errors.
=> Fix meridian offset

hydromt/data_adapter/geodataframe.py, hydromt/data_adapter/geodataset.py, hydromt/data_adapter/rasterdataset.py, hydromt/data_catalog.py, hydromt/gis_utils.py, make_env.py, pixi.toml
Fixes typing issue when hydromt.gis_utils is loaded in py39
```
ImportError while loading conftest '/home/runner/work/hydromt_sfincs/hydromt_sfincs/tests/conftest.py'.
tests/conftest.py:7: in <module>
from hydromt_sfincs.sfincs import SfincsModel
hydromt_sfincs/__init__.py:11: in <module>
from .sfincs import *
hydromt_sfincs/sfincs.py:14: in <module>
import hydromt
/usr/share/miniconda/envs/hydromt-sfincs-dev/lib/python3.[9](https://github.com/Deltares/hydromt_sfincs/actions/runs/6902656342/job/18779801237?pr=147#step:6:10)/site-packages/hydromt/__init__.py:17: in <module>
from . import cli, flw, raster, stats, vector, workflows
/usr/share/miniconda/envs/hydromt-sfincs-dev/lib/python3.9/site-packages/hydromt/flw.py:[12](https://github.com/Deltares/hydromt_sfincs/actions/runs/6902656342/job …
```
=> fix typing annotation for py39

docs/changelog.rst, hydromt/raster.py, tests/test_vector.py
Fixes #613 
Function was modified but did not account that input_crs could be directly of type CRS anymore
Also modified changelog to take into account release 0.9.1
=> Bugfix raster.set_crs

.github/workflows/docs.yml, .github/workflows/test-docker.yml, .github/workflows/tests.yml, .github/workflows/tests_pip.yml, docs/changelog.rst, docs/user_guide/data_overview.rst, hydromt/cli/main.py, tests/data/export_config.yml, tests/test_cli.py
Fixes #657 
- I ended up not allowing multiple instances of time tuples because that would end up either overwriting the previous exports, or changing the file names, which I didn't want to do. 
- Other changes are based on the discussion Hélène and I had.
=> Export improvements

docs/changelog.rst, hydromt/raster.py, tests/test_raster.py
Fixes #680
Somehow with `DataArray.map_blocks` methods turns the spatial_ref coordinate into a dask array. This method is used for reprojection of lazy arrays. When reprojecting from such DataArray the spatial_ref attributes get corrupted (not sure how or why). The solution is to simply avoid the spatial_ref coord to be lazy.
=> avoid lazy spatial ref coordinate

docs/changelog.rst, hydromt/models/model_api.py, tests/test_model.py
GeoJSON should be written with WGS84 coordinates according to the [2016 GeoJSON specs](https://datatracker.ietf.org/doc/html/rfc7946). Model.write_geoms() writes the geometries in model CRS normally. I added a option so that write_geoms can write GeoJSONs with WGS84 coordinates.
Fixes #510 
Added an to_wgs84 option in Model.write_geoms(). If set to True and the driver is GeoJSON the geometry will be set to EPSG:4326.
Also added a check in set_geoms so that new geometries are set to the model crs if the model has a crs. 
=> Write geojson file with WGS84 coordinates in Model.write_geoms()

docs/changelog.rst, docs/dev/plugin-quickstart.rst, hydromt/models/model_api.py, hydromt/models/model_grid.py, hydromt/models/model_vector.py
Fixes #694
Create an explicit initialize method for all model components. This supports the behaviour of reading the data upon initialization, but with and argument to skip this behaviour when called from the read_ method itself.
Not sure how to test this properly. But running the example in from the issue will confirm it works. 
=> avoid double reading

data/catalogs/changelog.rst, docs/_static/switcher.json, docs/changelog.rst, hydromt/__init__.py
Added
-----
- Export CLI now also accepts time tuples (#660)
- New stats.skills VE and RSR (#666)
- Check CLI command can now validate bbox and geom regions (#664)
- Added GADM 4.1 as FlatGeoBuff files to deltares_data catalog (#686)
Changed
-------
- Export CLI now uses '-s' for source, '-t' for time and '-i' for config. (#660)
Fixed
-----
- Removed deprecated entrypoints library. (#676)
- Bug in `raster.set_crs` if input_crs is of type CRS. (#659)
- Export CLI now actually parses provided geoms. (#660)
- Bug in stats.skills for computation of pbias and MSE / RMSE. (#666)
- `Model.write_geoms` ow has an option to write GeoJSON coordinates in WGS84 if specified (#510)
- Fix bug with lazy spatial_ref coordinate (#682)
- Bug in gis_utils.meridian_offset. (#692)
=> Release 0.9.2

.github/workflows/publish-docker.yml, .github/workflows/test-docker.yml
Fixes #712 
Tested with a manual workflow and it seems to work. Given how infrequently we have to build docker images I just disabled the caching in the workflow. I think this is fine, the image still built in a couple of minutes. 
=> remove load and caching from docker

data/catalogs/test_data_catalog.py, data/catalogs/test_new_datacatalog_item.py, docs/changelog.rst
Fixes #735 
I made a script for testing the predefined data catalogs. It works with command line arguments. For instance this call will test the chelsa dataset source of version 1.2:
`python path/to/datacatalog.yml -d chelsa -v 1.2`
This call will open the dataset and clip the dataset to a small bounding box if the dataset contains geo data. This can take some time. It also possible to supply your own bounding box with the -r flag. Bounding box must be a dict containing a list of xmin, ymin, xmax, ymax coordinates in EPSG 4326.
The script can also check if all the paths mentioned in the data catalog exist. This is done by calling the script and giving only the path to the data catalog.
The script will also always check if the given .yml is a valid data catalog.
Let me know if you have …
=> Add datacatalog test script

docs/changelog.rst, hydromt/data_adapter/rasterdataset.py, hydromt/raster.py, tests/test_data_adapter.py, tests/test_raster.py
Fixes #754
When reading GOCs, the `rioxarray.open_raster(..., overview_level=0)` opens the first overview which is zoom_level 1. To read the native resolution the `overview_level` level argument should not be used, and for actual zoom levels we can use `overview_level = zoom_level - 1`
=> fix COG zoom level bug

docs/changelog.rst, hydromt/models/model_api.py, tests/test_model.py
Fixes #425 
Added a save_csv option to Model.write_data_catalog.
=> Datacatalog to csv

hydromt/gis_utils.py, hydromt/io.py, tests/test_data_adapter.py, tests/test_io.py
Fixes #742
Stopped using the `.open` functionality on UPath. 
May break specific UPath options on other filesystems, but UPath breaks with geopandas. Should wait for v1 fix
=> geodataframe reading stop opening

.github/workflows/refresh-cache.yml, .github/workflows/tests.yml
N/A
Currently the tests are not run properly on the v1 branches. In addition because of how the caching works they cannot test on windows which is required for the cross platform tests. This should enable that. 
=> fix workflows and enable windows testing

docs/_static/switcher.json, docs/changelog.rst, hydromt/__init__.py
This release fixes several bugs. Most notably the `NoDataSrategy` is available in much more data reading methods so plugins can use it more directly. Additionally there are some bug fixes relating to reading shapefiles and reading COGs.
=> Release v0.9.3

.github/workflows/refresh-cache.yml, .github/workflows/tests.yml, tests/test_data_adapter.py
Fixes #774 
adjusting the mamba setup to work with the windows runner. The workflows need a cache that can't be generated until this PR is merged, so testing for now will be limited, but I did the testing in another repo where it worked, so it should all be good.
=> Fix windows tests

data/catalogs/artifact_data.yml, data/catalogs/aws_data.yml, data/catalogs/deltares_data.yml, data/catalogs/gcs_cmip6_data.yml, docs/changelog.rst, docs/user_guide/data_prepare_cat.rst, hydromt/__init__.py, hydromt/_validators/data_catalog.py, hydromt/data_catalog.py, tests/data/test_sources.yml, tests/test_data_catalog.py, tests/validators/test_data_catalog_validation.py
None so far that I am aware of
=> Data Catalog roots

docs/_static/switcher.json, docs/changelog.rst, hydromt/__init__.py
This release fixes a performance regression when reading geometry masks, relaxed warnings for empty raster datasets and updated the documention of the new hydromt commands.
Fixed
--------
- Added back geometry mask when reading vector files with `fiona` as engine/ driver. (#777)
- Relaxed empty data checking on `RasterDatasetAdapter`. (#782)
- Add documentation for `hydromt check` and `hydromt export` commands. (#767)
=> Release v0.9.4

.github/workflows/docs.yml
I accidentally removed the line where the build docs happened. The dummy docs are building fine, but the real deal was not. So I added the pixi command to actually build the docs to html. But it won't hit these lines when running it in a PR.
=> Actually build the docs when not a PR

.gitignore, .vscode/extensions.json, .vscode/launch.json, .vscode/settings.json
- Make it possible to debug pytest unit tests via vs code. I needed to set up a `purpose` in the `launch.json`.
- Share settings about auto-formatting that is workspace specific.
=> Vscode debugging

.github/workflows/tests.yml, .gitignore, .vscode/extensions.json, .vscode/launch.json, .vscode/settings.json, docs/changelog.rst, hydromt/gis/raster.py
=> Merge main to v1

docs/changelog.rst, hydromt/models/model_mesh.py, tests/test_model.py
None defined: MeshModel.get_mesh method returns error after xugrid update to 0.9.0
```
hydromt/models/components/mesh.py:369: in get_mesh
uds[var] = self.data[var]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <xarray.Dataset> Size: 386kB
Dimensions:        (mesh2d_nNodes: 2790, mesh2d_nFaces: 5248,
mesh2d_...int64 42kB 0 1 2 3 4 ... 5244 5245 5246 5247
Data variables:
*empty*
Attributes:
Conventions:  CF-1.9 UGRID-1.0
key = 'elevation'
value = <xarray.DataArray 'elevation' (mesh2d_nFaces: 5248)> Size: 21kB
[5248 values with dtype=float32]
Coordinates:
mesh...2kB ...
* mesh2d_nFaces  (mesh2d_nFaces) int64 42kB 0 1 2 3 4 ... 5244 5245 5246 5247
Attributes:
unit:     m NAP
def __setitem__(self, key, value):
if isinstance(value, UgridDataArray): …
```
=> fix get_mesh after xugrid update

hydromt/components/tables.py, hydromt/utils/__init__.py, hydromt/utils/constants.py, tests/components/test_tables_component.py, tests/models/test_model.py
Fixes #864
In today's refinement we decided that components should take some variation of `default_filename` at init, and store that so it can be used for reading and writing unless the user overrides it by passing in an argument of their own.
In addition we did not explicitly discuss today, but it seems we have reached a consensus that:
- components that can contain multiple objects (e.g. they store a dictionary of something) should be names in plural form
- We do not want to expose constants for our default paths. 
This PR brings `TablesComponent` up to date with that convention. I don't think any of the changelogs or documentation has to be updated for this, but feel free to let me know if you disagree. 
=> Implement default file path pattern for tables component

docs/changelog.rst, hydromt/data_adapter/rasterdataset.py, tests/test_data_adapter.py
Fixes #881
Variables on datasets with only a single variable were not checked. The reason was that we want to automatically convert variable names from tif files (which get the file name as variable by default) if a variable is requested. This is important to make sure we can still read tif files based on the path if not set in the data catalog without getting errors on the variable name. I have moved this functionality to the raster driver and now make sure the check for variables always occurs.
@Jaapel this behaviour should also land in #857
=> fix renaming issue

docs/changelog.rst, hydromt/vector.py, tests/test_vector.py
Fixes #830 
Singe geometry geodatasets with zero dimensions are not discovered. While we can fix this it provides many other issues downstream as we also need a index dimension name which does not exist in this case. Hence I went with improving the GeoDataset typing and error messages.
=> fix error message for 0D geometry variable in GeoDataset

data/catalogs/deltares_data.yml
=> add EOBS v29.0e deltares_data.yml

docs/api.rst, hydromt/_typing/__init__.py, hydromt/_typing/type_def.py, hydromt/data_catalog.py, hydromt/data_source/data_source.py, hydromt/data_source/geodataframe.py, hydromt/data_source/rasterdataset.py, hydromt/drivers/base_driver.py, hydromt/drivers/geodataframe_driver.py, hydromt/drivers/netcdf_driver.py, hydromt/drivers/pyogrio_driver.py, hydromt/drivers/rasterdataset_driver.py, hydromt/drivers/zarr_driver.py, hydromt/gis/utils.py, hydromt/metadata_resolver/convention_resolver.py, hydromt/metadata_resolver/metadata_resolver.py, tests/conftest.py, tests/data_sources/test_data_source.py, tests/data_sources/test_geo_data_frame_source.py, tests/data_sources/test_raster_dataset_source.py, tests/drivers/test_pyogrio_driver.py
Fixes #874 #902 
- transform (mask, bbox, buffer) to mask early on in Source to reduce arguments downstream
- remove unnecessary arguments 
- create `Driver.read_data` method to avoid duplication of identical code to resolve the uris in `Driver.read`
- remove align argument from DataCatalog.get_rasterdataset, fixes #874
=> small refactor driver

.github/workflows/check-data-catalogs.yml, .github/workflows/docs.yml, .github/workflows/pixi_auto_update.yml, .github/workflows/tests.yml
Update pixi to the latest version so people with multiple Deltares repositories on their PC don't have to switch pixi versions.
=> Update pixi to 0.21.1

.gitattributes
=> Updated .gitattributes for working with yaml files on Windows

docs/api.rst, docs/changelog.rst, hydromt/drivers/raster/rasterdataset_driver.py, hydromt/drivers/raster/rasterio_driver.py, hydromt/metadata_resolver/convention_resolver.py, hydromt/metadata_resolver/metadata_resolver.py, hydromt/metadata_resolver/raster_tindex_resolver.py, tests/metadata_resolvers/test_raster_tindex_resolver.py
=> Add URI resolver for raster_tindex files

docs/changelog.rst, hydromt/stats/design_events.py, tests/test_stats_design_events.py
An index error was raised when the number of peaks varies between stations. This could occur in real data and should be dealt with in the code.
Limit the maximum index per station to the number of peaks.
=> bugfix in hydrograph_1d method

.gitattributes
The widcard in the git attributes to enforce correct line endings was misscpecified. we specified it as `*.yaml` and we should have included `*.yml`. This PR fixes that. 
=> added .yml to gitattributes

.github/workflows/test_error_free.yml, hydromt/drivers/base_driver.py, hydromt/drivers/dataframe/pandas_driver.py, hydromt/drivers/geodataframe/pyogrio_driver.py, hydromt/drivers/geodataset/xarray_driver.py, hydromt/drivers/raster/raster_xarray_driver.py, pixi.toml, tests/conftest.py, tests/data_sources/test_geo_dataframe_source.py, tests/data_sources/test_geo_dataset_source.py, tests/data_sources/test_raster_dataset_source.py
Apparently pydantic doesn't like you overriding the class vars of parents. As I think it is important to stay warning free, I added a pixi test job and a (non-required) ci job to make sure that the test suite remains warning free.  We can also always allow/ignore warnings that we think are acceptable in the `pyproject.toml` 
=> Fix warnings

docs/changelog.rst, hydromt/_validators/data_catalog.py, hydromt/cli/_utils.py, hydromt/data_catalog/adapters/data_adapter.py, hydromt/data_catalog/data_catalog.py, hydromt/gis/flw.py, hydromt/model/processes/basin_mask.py, tests/_validators/test_data_catalog_validation.py, tests/gis/test_flw.py, tests/workflows/test_basin_mask.py
Fixes #561
Fixes #566
Fixes #562 
Fixes #559
Fixes #549
Just remove the code associated with the deprecation warnings. All functionalities were already in some other place, so just removing the code is enough I think.
=> remove remaining deprecation warnings

hydromt/data_catalog/adapters/dataset.py, hydromt/data_catalog/adapters/rasterdataset.py, hydromt/data_catalog/data_catalog.py, hydromt/data_catalog/sources/dataset.py, hydromt/data_catalog/sources/rasterdataset.py, hydromt/model/processes/region.py, tests/data_catalog/adapters/test_data_adapter.py, tests/data_catalog/sources/conftest.py, tests/data_catalog/sources/test_common_functionality.py, tests/data_catalog/sources/test_dataframe_source.py, tests/data_catalog/sources/test_dataset_source.py, tests/data_catalog/sources/test_geo_dataframe_source.py, tests/data_catalog/sources/test_geo_dataset_source.py, tests/data_catalog/sources/test_raster_dataset_source.py
Many repeating tests using boilerplate
Using `pytest.mark.parametrize` we can reduce the lines of code and test interfaces effectively.
=> Parametrize source tests

hydromt/data_catalog/drivers/geodataset/vector_driver.py
Fixes #983 
Predicate argument is still needed. I have added it in the `geodataset_vector`,  `GeoDatasetDriver`. We can implement these for geodataframe drivers in the future
=> use predicate arg in vector driver

hydromt/_typing/__init__.py, hydromt/_typing/error.py, hydromt/data_catalog/data_catalog.py, hydromt/data_catalog/sources/dataframe.py, hydromt/data_catalog/sources/dataset.py, hydromt/data_catalog/sources/geodataframe.py, hydromt/data_catalog/sources/geodataset.py, hydromt/data_catalog/sources/rasterdataset.py, tests/data_catalog/sources/test_dataset_source.py, tests/data_catalog/sources/test_geo_dataframe_source.py, tests/data_catalog/test_data_catalog.py
Fixes #1036 
HandleNodataStrategy is much more widely used in the driver side, while ErrorHandlingMethod was only really really used for stac. Thefore we're deprecating the latter in favour of the former
=> remove ErrorHandlingMethod in favour of NoDataStrategy

data/predefined_catalogs.yml
Reference to main in old catalog format
=> fix catalog reference to correct hash

.github/workflows/docs.yml, .github/workflows/finish-release.yml
Fixes #1071 
the pixi command was outdated (`html` is now `docs`) so I removed that. 
Aside from that I also think the docs version hasn't been detected correctly for a bit, leading to previous docs disappearing with some more explicit bash this should be at least noticed sooner I think. I'll revert previous versions soon 
=> fix docs and clean up finish release

hydromt/__init__.py
Fixes #1093 
post release the version number was updated incorrectly making two validation tests fail. This should fix them again
=> bump version to v1.0.1.dev0

docs/changelog.rst, hydromt/model/components/geoms.py, tests/components/test_geoms_component.py
Fixes #1079
My steps:
- added the assertion of `geom_component._region_data()`, since calling that property shows the current bug (fails with `IndexError: index 1 is out of bounds for axis 0 with size 1`)
- solved the IndexError by properly generating `total_bounds` (was calling over the wrong dimension)
- this caused the error `box() missing 3 required positional arguments: 'miny', 'maxx', and 'maxy'` one line below
- solved by adding `*` to expand the `total_bounds` argument form a tuple into four separate arguments
- this resulted in `shapely.errors.GeometryTypeError: Unknown geometry type: 'featurecollection'` >> solved by generating the geodataframe like in `test_model_set_geoms`, but I have no clue if this results in the expected type/format. At least it works, but please check this …
=> fix `geom_component._region_data()`

.binder/Dockerfile, Dockerfile, docs/changelog.rst
Fixes #1098
The dockerfile for the binder integration seemingly hasn't been updated since we moved to pixi since it still references mamba. Updating it to use pixi solved the issue. 
=> Fix binder integration

.github/workflows/tests.yml
Currently tests are not run automatically when the pixi workflow runs to update the dependencies. this should fix that
=> fix(ci): make sure tests run after pixi auto update

.sonarcloud.properties, README.rst
Fixes #1124 
Add `.sonarcloud.properties` file with python version and test folder. Stick with automatic analysis.
=> Add sonarcloud properties for tests and python versions

hydromt/_utils/caching.py, pixi.lock, pyproject.toml
Fixes #1119
Because we moved to pypi dependencies, I had to tell pyproject.toml that we also need `fsspec[http]`.
And there seems to be no such `kwarg` called `block_size`. This was removed long time ago from `aiohttp`. So removing `block_size` from `fs.get()` seems to resolve the problem.
=> Fix 1119 request block size

hydromt/data_catalog/drivers/base_driver.py
`Driver` now load `URIResolver` plugins by accident.
Found it while looking up some pydantic details for another repo :)
=> mistake in driver plugin loader

.github/workflows/sonar.yml, .github/workflows/tests.yml, .sonarcloud.properties, sonar-project.properties
Add code coverage support
Fixes #1077
We have migrated to SonarQube Cloud, and it also supports code coverage. So we want to have all the information in one place.
=> Setup SonarQube via CLI scanning

docs/changelog.rst, hydromt/gis/raster.py, hydromt/model/processes/grid.py, tests/gis/test_raster.py
Fixes #1121 
As mentioned the rotated grid creation returned the dimensions flipped as was reported in the docstring. I added a simple test to solidfy which shapes we should return here 
=> Return correct dims of rotated grid constructed from geom

docs/changelog.rst, hydromt/gis/_gis_utils.py, hydromt/model/processes/grid.py, tests/gis/test_raster.py
Fixes #1120 
to guess the nearest `UTM` crs the bounds need to be provided in 4326. Previously the bounds were provided in the region crs. To avoid having to reproject twice, we transform the bounds "manually" 
=> transform totalbounds to 4326 before trying to guess utm

hydromt/data_catalog/data_catalog.py
Fixes #1166 
Currently a Path object could be passed on to a DataFrameSource object for the uri argument in the DataCatalog.get_dataframe method. This will cause an validation error because DataFrameSource only accepts a string for the uri argument. I casted the path variable to a string to fix this. In all other get_data methods this was done as well, but someone forgot to add this to the get_dataframe method apparently. 
=> fixes calling DataCatalog.get_dataframe with path object 

docs/changelog.rst, hydromt/model/components/config.py, tests/components/test_config_component.py
When I was working on the sonarcube issues, I noticed that we lacked test coverage for a config component that is given a default template, which is probably also why we didn't cover that case. This PR fixes that. 
There was no issue for this, but I'm happy to make one if the reviewer would like to see one. 
=> Add tests for components with default template

hydromt/model/model.py, hydromt/model/processes/meteo.py
Fixes #1212 
fixed two bugs:
- If a `hydromt_step` was called without any arguments in a .yml file, `Model.build()` will throw a TypeError.
- Also resolved broken typehints in meteo.py
=> Resolve error related to parameter merging in Model.build() and update xarray imports in meteo module

docs/changelog.rst, hydromt/_io/__init__.py, hydromt/_io/readers.py, hydromt/_io/writers.py, hydromt/_utils/caching.py, hydromt/model/components/datasets.py, hydromt/model/components/grid.py, hydromt/model/components/mesh.py, hydromt/model/components/spatialdatasets.py, hydromt/model/components/vector.py, tests/components/test_grid_component.py
Added compression and CF compliant dimensions encoding to `_write_nc`. Also added the option do to delay the compute of the datasets and use a dask progressbar instead. Also made `_write_nc` write a single file a simple loop over the data of the components where necessary. This in order to take away the footfun that was the encoding in the old `_write_nc`. Separated `_read_nc` into  `_read_nc` for a single file and `_read_ncs` for the read of multiple files using a pattern.
=> Clarify and update write and read nc

hydromt/data_catalog/adapters/dataframe.py, hydromt/data_catalog/adapters/geodataframe.py, pixi.lock, tests/conftest.py, tests/data_catalog/adapters/test_dataframe_adapter.py, tests/data_catalog/sources/test_geo_dataframe_source.py, tests/data_catalog/test_data_catalog.py
Turn on pd.options.mode.copy_on_write to enable higher performance pandas usage and resolve bugs/errors related to this.
Fixes #1235
Used an editable install of `hydromt:main` and `hydromt_wflow:fix/re-enable-tests-again` and ran the hydromt_wflow tests.
This lead to the SettingWithCopyWarning being raised in the (geo)dataframe adapters as mentioned in the issue.
This has now been resolved, and doing this is disabled by the copy_on_write setting, and will error.
=> Resolve SettingWithCopyWarnings hidden in (geo)dataframe adapters

.vscode/launch.json, docs/changelog.rst, hydromt/_io/__init__.py, hydromt/_io/writers.py, hydromt/model/components/base.py, hydromt/model/components/config.py, hydromt/model/components/datasets.py, hydromt/model/components/geoms.py, hydromt/model/components/grid.py, hydromt/model/components/mesh.py, hydromt/model/components/spatial.py, hydromt/model/components/spatialdatasets.py, hydromt/model/components/tables.py, hydromt/model/components/vector.py, tests/components/test_config_component.py, tests/components/test_grid_component.py, tests/components/test_mesh_component.py, tests/components/test_vector_component.py, tests/conftest.py, tests/data_catalog/test_data_catalog.py, tests/io/test_io.py
Fixes #1239
Last part of #1239 that harmonizes the write function's logging capabilities. All components are now sending info to the logger.
Also ensured to use pathlib more than os to do the file path manipulations.
=> Harmonize write functions

hydromt/data_catalog/drivers/geodataframe/pyogrio_driver.py
Fixes #1238 
Data catalog crs should only be used if not defined within the file attributes itself.
While checking other drivers, crs conversion is actually (properly) done in self.transform so in the data adapters rather than in the drivers. There the behavior is as expected.
So I removed this incorrect part form geodataframe driver.
=> crs from geodataframe has priority over catalog crs
